### PR TITLE
Fix link for Javascript API

### PR DESCRIPTION
**Pull request by windley**
I think it's pointing to the right plance now.

### CODE REVIEW

**Comment by scripting** [comment]
Phil, thanks for the note. I made the fix. In general, I prefer bug reports over pull requests, because I write this stuff with my outliner, not in straight text. Everything you see here is generated from the outline structure.

**Comment by windley** [comment]
OK, that’s cool. When you say “bug report” do you mean an email or something else? 

BTW, I saw your note on the noise your geothermal system makes. Is it a water hammer? If that fits the symptoms, then you should be able to get some relief with the help of a plumber installing a water hammer arrestor.

**Comment by scripting** [comment]
Best thing to do is to report an Issue on the github repo. I'm notified,
and it's a good place to create a record.

I think we got to the bottom of the problem with the geothermal system just
this morning,. I found a contractor run by nerds, and that's pretty much
what it takes here. There's real science here.

The sound is a valve without a buffer. So the water fills the pipe at very
high pressure. The buffer should mostly eliminate that, and moving the
valve to the edge of the basement should move the sound outside.

The tech is still new, and people who don't understand it are installing
it.

**Comment by windley** [comment]
Got it on issues. 

> On Oct 30, 2019, at 10:57 AM, Dave Winer <notifications@github.com> wrote:
> 
> 
> The tech is still new, and people who don't understand it are installing
> it.

What could possibly go wrong?!? :)

**Pull request closed without merging**
